services:
  retromonkey:
    build: .
    container_name: retromonkey
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///retromonkey.db
    volumes:
      - ./instance/retromonkey.db:/app/instance/retromonkey.db
      - ./retromonkey/static/images:/app/retromonkey/static/images
      - ./instance/gmail_tokens.json:/app/instance/gmail_tokens.json
